const scrollTypes = [ "scroll","onwheel", "wheel", "mousewheel", "onmousewheel","DOMMouseScroll", "touchstart", "touchmove", "touchend", "touchcancel" ];
const keys = {37: 1, 38: 1, 39: 1, 40: 1};
/* 
* Scroll-locking function for closed-scroll pages
* Thanks to gblazex @ https://stackoverflow.com/users/378024/gblazex
* Pure JS no jQuery 
* https://stackoverflow.com/a/4770179
* Partially modified to suit my needs here
*/
function preventDefault(e){e.preventDefault();}function preventDefaultForScrollKeys(e){if (keys[e.keyCode]){preventDefault(e); return false;}}var supportsPassive=false;try{window.addEventListener( "test", null, Object.defineProperty({}, "passive",{get: function (){supportsPassive=true;},}) );}catch (e){}var wheelOpt=supportsPassive ?{passive: false}: false;var wheelEvent="onwheel" in document.createElement("div") ? "wheel" : "mousewheel";var arrow_keys_handler=function (e){switch (e.keyCode){case 37: case 39: case 38: case 40: case 32: e.preventDefault(); break; default: break;}};function disableScroll(){scrollTypes.forEach(function (current){window.removeEventListener(current, onScrollEvent, false); window.removeEventListener(current, onScrollEvent, wheelOpt);}); window.removeEventListener("keydown", onKeyEvent, false); window.addEventListener("keydown", arrow_keys_handler, false); window.addEventListener("onwheel", preventDefault, false); window.addEventListener("onmousewheel", preventDefault, false); window.addEventListener("mousewheel", preventDefault, false); window.addEventListener("DOMMouseScroll", preventDefault, false); window.addEventListener(wheelEvent, preventDefault, wheelOpt); window.addEventListener("wheel", preventDefault, wheelOpt); window.addEventListener("touchstart", preventDefault, wheelOpt); window.addEventListener("touchmove", preventDefault, wheelOpt); window.addEventListener("touchend", preventDefault, wheelOpt); window.addEventListener("keydown", preventDefaultForScrollKeys, false);}function enableScroll(){window.removeEventListener("onwheel", preventDefault, false); window.removeEventListener("onmousewheel", preventDefault, false); window.removeEventListener("mousewheel", preventDefault, false); window.removeEventListener("DOMMouseScroll", preventDefault, false); window.removeEventListener(wheelEvent, preventDefault, wheelOpt); window.removeEventListener("wheel", preventDefault, wheelOpt); window.removeEventListener("touchstart", preventDefault, wheelOpt); window.removeEventListener("touchmove", preventDefault, wheelOpt); window.removeEventListener("touchend", preventDefault, wheelOpt); window.removeEventListener("keydown", preventDefaultForScrollKeys, false);}
/* 
 * jQuery Line-splitting 
 * Function for text-based interactions 
 * https://github.com/jeremyharris/split_lines
 * MIT License (http://www.opensource.org/licenses/mit-license.php)
 * jQuery 1.4.2 or later
 */
(function($){function _createTemp(element){return element.clone().css({position: 'absolute'});};function _splitHtmlWords(contents){var words=[];var splitContent;for (var c=0; c<contents.length; c++){if (contents[c].nodeName==='BR'){words.push('<br>');continue;}if (contents[c].nodeType==3){splitContent=_splitWords(contents[c].textContent || contents[c].toString());}else{var tag=$(contents[c]).clone();splitContent=_splitHtmlWords(tag.contents());for (var t=0; t<splitContent.length; t++){tag.empty();splitContent[t]=tag.html(splitContent[t]).wrap('<p></p>').parent().html();}}for (var w=0; w<splitContent.length; w++){if (splitContent[w]===''){continue;}words.push(splitContent[w]);}}return words;};function _splitWords(text){return text.split(/\s+/);}function _markupContent(tag, html, index){tag='<div class="stop">' + tag;var $outer=$(tag).find('*:not(:has("*"))').html(html).closest('.stop').slice(-1);$outer.children().each(function (i, element){element.style.setProperty('--line-index', index);});return $outer.html();}$.fn.splitLines=function(options){var settings={width: 'auto',tag: '<div>',wrap: '',keepHtml: true};if (options){$.extend(settings, options);}var newHtml=_createTemp(this);var contents=this.contents();var text=this.text();this.append(newHtml);newHtml.text('42');var maxHeight=newHtml.height()+2;newHtml.empty();var tempLine=_createTemp(newHtml);var width=settings.width;if (settings.width==='auto'){width=this[0].offsetWidth;}tempLine.width(width);this.append(tempLine);var words=settings.keepHtml ? _splitHtmlWords(contents) : _splitWords(text);var prev;var lineCount=0;for (var w=0; w<words.length; w++){var html=tempLine.html();tempLine.html(html+words[w]+' ');if (tempLine.html()==prev){prev='';newHtml.append(_markupContent(settings.tag, tempLine.html(), lineCount));tempLine.html('');continue;}if (tempLine.height() > maxHeight){prev=tempLine.html();tempLine.html(html);newHtml.append(_markupContent(settings.tag, tempLine.html(), lineCount));tempLine.html('');w--;lineCount++;}}newHtml.append(_markupContent(settings.tag, tempLine.html(), lineCount));this.html(newHtml.html());};})(jQuery);
/*
 * jQuery WidowFix Plugin
 * http://matthewlein.com/widowfix/
 * Copyright (c) 2010 Matthew Lein
 * Version: 1.3.2 (7/23/2011)
 * Dual licensed under the MIT and GPL licenses
 * jQuery v1.4 or later
(function(a){jQuery.fn.widowFix=function(d){var c={letterLimit:null,prevLimit:null,linkFix:false,dashes:false};var b=a.extend(c,d);if(this.length){return this.each(function(){var i=a(this);var n;if(b.linkFix){var h=i.find("a:last");h.wrap("<var>");var e=a("var").html();n=h.contents()[0];h.contents().unwrap()}var f=a(this).html().split(" "),m=f.pop();if(f.length<=1){return}function k(){if(m===""){m=f.pop();k()}}k();if(b.dashes){var j=["-","–","—"];a.each(j,function(o,p){if(m.indexOf(p)>0){m='<span style="white-space:nowrap;">'+m+"</span>";return false}})}var l=f[f.length-1];if(b.linkFix){if(b.letterLimit!==null&&n.length>=b.letterLimit){i.find("var").each(function(){a(this).contents().replaceWith(e);a(this).contents().unwrap()});return}else{if(b.prevLimit!==null&&l.length>=b.prevLimit){i.find("var").each(function(){a(this).contents().replaceWith(e);a(this).contents().unwrap()});return}}}else{if(b.letterLimit!==null&&m.length>=b.letterLimit){return}else{if(b.prevLimit!==null&&l.length>=b.prevLimit){return}}}var g=f.join(" ")+"&nbsp;"+m;i.html(g);if(b.linkFix){i.find("var").each(function(){a(this).contents().replaceWith(e);a(this).contents().unwrap()})}})}}})(jQuery);
*/